package com.example.finance;

import android.content.Context;
import android.os.Handler;
import android.os.Looper;

import java.util.List;
import java.util.Locale;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class ReportManager {
    public interface ReportCallback {
        void onComplete(SendStatus status);
    }

    public enum SendStatus {
        SENT,
        SKIPPED,
        FAILED
    }

    public static void sendReportAsync(Context context, String reportDate, String reportKind,
                                       String generatedBy, boolean markDailySent,
                                       ReportCallback callback) {
        ExecutorService executorService = Executors.newSingleThreadExecutor();
        executorService.execute(() -> {
            SendStatus status = sendReportBlocking(context, reportDate, reportKind, generatedBy, markDailySent);
            new Handler(Looper.getMainLooper()).post(() -> callback.onComplete(status));
        });
    }

    public static SendStatus sendReportBlocking(Context context, String reportDate, String reportKind,
                                                String generatedBy, boolean markDailySent) {
        StockDatabaseHelper dbHelper = new StockDatabaseHelper(context);

        if (markDailySent && dbHelper.hasDailyReportBeenSent(reportDate)) {
            return SendStatus.SKIPPED;
        }

        List<String> recipients = dbHelper.getActiveReportRecipientEmails();
        if (!Communication.hasEmailConfiguration(context) || recipients.isEmpty()) {
            return SendStatus.FAILED;
        }

        String subject = buildSubject(context, reportDate, reportKind);
        String body = buildBody(context, dbHelper, reportDate, reportKind, generatedBy);
        boolean success = Communication.sendEmailBlocking(context, subject, body, recipients);

        if (!success) {
            return SendStatus.FAILED;
        }

        dbHelper.recordReportSent(reportDate, reportKind);
        return SendStatus.SENT;
    }

    private static String buildSubject(Context context, String reportDate, String reportKind) {
        String tavernName = Utils.getTavernName(context);
        String suffix;
        switch (reportKind) {
            case StockDatabaseHelper.REPORT_KIND_STORE_CLOSE:
                suffix = "Store Close Report";
                break;
            case StockDatabaseHelper.REPORT_KIND_MIDNIGHT_AUTO:
                suffix = "Automatic Daily Report";
                break;
            default:
                suffix = "Full Report";
                break;
        }
        return tavernName + " " + suffix + " for " + reportDate;
    }

    private static String buildBody(Context context, StockDatabaseHelper dbHelper, String reportDate,
                                    String reportKind, String generatedBy) {
        double totalAmount = dbHelper.getSumOfSellingPrice(reportDate);
        String mostSoldItem = dbHelper.getMostAppearingItemWithSizeForDate(reportDate);
        String salesReport = dbHelper.getSalesReportForDate(reportDate);
        String lowStockItems = dbHelper.getLowStockItems();
        Integer globalThreshold = dbHelper.getGlobalLowStockThreshold();

        StringBuilder bodyBuilder = new StringBuilder();
        bodyBuilder.append("Daily sales report for ").append(Utils.getTavernName(context)).append("\n\n")
                .append("Report date: ").append(reportDate).append("\n")
                .append("Generated by: ").append(generatedBy).append("\n")
                .append("Trigger: ").append(getTriggerLabel(reportKind)).append("\n")
                .append("Total Sales Amount: R")
                .append(String.format(Locale.getDefault(), "%.2f", totalAmount)).append("\n")
                .append("Best Selling Item: ").append(mostSoldItem != null ? mostSoldItem : "No sales today").append("\n")
                .append("Low stock mode: ")
                .append(globalThreshold != null && globalThreshold > 0
                        ? "Global threshold of " + globalThreshold
                        : "10% fallback of received stock")
                .append("\n\n")
                .append(lowStockItems)
                .append("\n")
                .append(salesReport)
                .append("\nGenerated at ").append(Utils.getCurrentDateTime()).append(".\n");

        return bodyBuilder.toString();
    }

    private static String getTriggerLabel(String reportKind) {
        switch (reportKind) {
            case StockDatabaseHelper.REPORT_KIND_STORE_CLOSE:
                return "Store close";
            case StockDatabaseHelper.REPORT_KIND_MIDNIGHT_AUTO:
                return "Automatic midnight fallback";
            default:
                return "Manual full report";
        }
    }
}
